# Generated by Django 5.1.11 on 2026-01-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='登録No')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性'), ('X', 'その他')], max_length=1, null=True, verbose_name='性別')),
                ('education', models.CharField(max_length=40, verbose_name='学歴')),
                ('qualification', models.CharField(blank=True, max_length=100, null=True, verbose_name='資格')),
                ('availability', models.CharField(blank=True, max_length=40, null=True, verbose_name='稼動')),
                ('affiliation', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属')),
                ('nearest_station', models.CharField(max_length=40, verbose_name='最寄駅')),
                ('specialty_field', models.CharField(blank=True, max_length=200, null=True, verbose_name='得意分野')),
                ('specialty_tech', models.CharField(blank=True, max_length=200, null=True, verbose_name='得意技術')),
                ('specialty_business', models.CharField(blank=True, max_length=200, null=True, verbose_name='得意業務')),
                ('self_pr', models.CharField(blank=True, max_length=500, null=True, verbose_name='自己PR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'パーソナル情報',
                'verbose_name_plural': 'パーソナル情報',
                'db_table': 'skill_sheet_personal',
            },
        ),
        migrations.CreateModel(
            name='SkillSheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='案件名')),
                ('content', models.TextField(verbose_name='内容')),
                ('remote', models.BooleanField(default=False, verbose_name='リモート')),
                ('start_month', models.CharField(max_length=6, verbose_name='開始年月')),
                ('end_month', models.CharField(max_length=6, verbose_name='終了年月')),
                ('duration', models.IntegerField(verbose_name='期間')),
                ('lang', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lang')),
                ('db', models.CharField(blank=True, max_length=200, null=True, verbose_name='DB')),
                ('os', models.CharField(blank=True, max_length=200, null=True, verbose_name='OS')),
                ('tools', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tools')),
                ('process1', models.BooleanField(default=False, verbose_name='Process1')),
                ('process2', models.BooleanField(default=False, verbose_name='Process2')),
                ('process3', models.BooleanField(default=False, verbose_name='Process3')),
                ('process4', models.BooleanField(default=False, verbose_name='Process4')),
                ('process5', models.BooleanField(default=False, verbose_name='Process5')),
                ('process6', models.BooleanField(default=False, verbose_name='Process6')),
                ('process7', models.BooleanField(default=False, verbose_name='Process7')),
                ('person1', models.IntegerField(default=0, verbose_name='Person1')),
                ('person2', models.IntegerField(default=0, verbose_name='Person2')),
                ('person3', models.IntegerField(default=0, verbose_name='Person3')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sheets', to='skill_sheet.personalinfo', verbose_name='パーソナルID')),
            ],
            options={
                'verbose_name': 'スキルシート詳細',
                'verbose_name_plural': 'スキルシート詳細',
                'db_table': 'skill_sheet_data',
                'ordering': ['-start_month'],
            },
        ),
    ]
