# Generated by Django 5.1.11 on 2026-01-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsheetdata',
            name='scope',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='担当工程'),
        ),
    ]
