# Generated by Django 5.1.11 on 2026-01-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_sheet', '0002_skillsheetdata_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsheetdata',
            name='work_style',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='業務形態'),
        ),
    ]
