# Generated by Django 5.1.11 on 2026-01-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_sheet', '0003_skillsheetdata_work_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='self_pr',
            field=models.TextField(blank=True, null=True, verbose_name='自己PR'),
        ),
    ]
