# Generated by Django 5.1.15 on 2026-08-07 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_sheet', '0004_alter_personalinfo_self_pr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ローカル設定ファイルから参照する識別子。英数記号のみ。', max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_.\\-]{0,63}$', message='名称は英字で始まり、英数字と _ . - のみが使えます（64文字以内）。')], verbose_name='名称')),
                ('label', models.CharField(help_text='日本語可。画面とエラーメッセージで使う。', max_length=100, verbose_name='表示名')),
                ('model_label', models.CharField(help_text='skill_sheet.PersonalInfo の形式。', max_length=100, verbose_name='対象モデル')),
                ('field_name', models.CharField(max_length=64, verbose_name='対象フィールド')),
                ('record_id', models.IntegerField(verbose_name='レコードID')),
                ('writable', models.BooleanField(default=False, help_text='push（ローカル→DB）を許可する場合のみチェック。既定は読み取り専用。', verbose_name='書き込み許可')),
                ('description', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'セル同期定義',
                'verbose_name_plural': 'セル同期定義',
                'db_table': 'skill_sheet_cell_binding',
                'ordering': ['name'],
            },
        ),
    ]
