# Generated by Django 5.1.15 on 2026-07-23 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ログイン日時')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='ユーザーエージェント')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ログイン履歴',
                'verbose_name_plural': 'ログイン履歴',
                'ordering': ('-logged_in_at', '-id'),
                'indexes': [models.Index(fields=['user', '-logged_in_at'], name='accounts_lo_user_id_78efc3_idx')],
            },
        ),
    ]
