# Generated by Django 5.1.15 on 2026-08-06 02:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=191, unique=True, verbose_name='ロックキー')),
                ('fail_count', models.PositiveIntegerField(default=0, help_text='ログイン成功でのみ0に戻る（時間経過では戻さない）', verbose_name='連続失敗回数')),
                ('fail_total', models.PositiveIntegerField(default=0, verbose_name='累計失敗回数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='ロック解除日時')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True, verbose_name='最終失敗日時')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最終失敗IP')),
            ],
            options={
                'verbose_name': 'ログインロック',
                'verbose_name_plural': 'ログインロック',
                'ordering': ('-last_failed_at',),
            },
        ),
        migrations.CreateModel(
            name='MeetingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='商談名・相手先')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='トークンハッシュ')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発行日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='最終アクセス')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='失効日時')),
                ('revoked_reason', models.CharField(blank=True, choices=[('manual', '手動失効'), ('lockout', '失敗回数超過')], default='', max_length=20, verbose_name='失効理由')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='メモ')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_meeting_accesses', to=settings.AUTH_USER_MODEL, verbose_name='発行者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_accesses', to=settings.AUTH_USER_MODEL, verbose_name='紐づくユーザー')),
            ],
            options={
                'verbose_name': '商談用アクセス',
                'verbose_name_plural': '商談用アクセス',
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='meeting_access',
            field=models.ForeignKey(blank=True, help_text='商談用トークン経由のログインならその発行分。ID/PWログインならNULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_histories', to='accounts.meetingaccess', verbose_name='商談用アクセス'),
        ),
    ]
