"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# defaultを持たせない。未設定なら decouple が UndefinedValueError を送出して起動に失敗する。
SECRET_KEY = config('SECRET_KEY')

# defaultはFalse（fail-safe）。設定漏れがトレースバック・環境変数の公開に直結しないようにする。
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
    cast=lambda v: [s.strip() for s in v.split(',')],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'accounts.apps.AccountsConfig',
    'app.home.apps.HomeConfig',
    'app.skill_sheet.apps.SkillSheetConfig',
    "app.download",
    "app.rag_tr_tool",
    "app.work_shift.apps.WorkShiftConfig",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 既定でログイン必須にする（Django 5.1 標準）。公開してよいビューだけが
    # @login_not_required を付けて明示的に開ける。
    #   アプリごとに login_required を付けて回る方式は付け漏れが起きる。実際に
    #   rag_tr_tool と skill_sheet が未認証で全公開されていた。
    #   既定を反転させ、新しいアプリを足しても自動的に保護される状態にする。
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS はアプリ内蔵テンプレート(APP_DIRS)より優先して検索される。
        # django.contrib.admin が同梱する registration/*.html を確実に上書きするために必要。
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "app.rag_tr_tool.context_processors.current_project",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='portfolio_db'),
        'USER': config('DB_USER', default='portf_admin'),
        'PASSWORD': config('DB_PASSWORD', default='portf_pass'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/'

# ---------------------------------------------------------------------------
# ログイン試行のロック（ID/PW・商談用トークンの両方に適用）
#   閾値は運用しながら調整する前提なので、すべて .env から変更できるようにする。
#   カウンタは成功時のみリセット（時間窓で自然回復させると総当たりを素通しするため）。
# ---------------------------------------------------------------------------
# 連続何回の失敗でロックするか
LOGIN_LOCK_THRESHOLD = config('LOGIN_LOCK_THRESHOLD', default=5, cast=int)
# 最初のロック秒数。以降の失敗ごとに倍化する
LOGIN_LOCK_SECONDS = config('LOGIN_LOCK_SECONDS', default=60, cast=int)
# 倍化の上限秒数
LOGIN_LOCK_MAX_SECONDS = config('LOGIN_LOCK_MAX_SECONDS', default=3600, cast=int)
# ロックの単位: 'user_ip'（ユーザー名+IP。既定）/ 'user'（ユーザー名のみ）
#   'user' は分散攻撃に強い反面、第三者が管理者を締め出せてしまう（自DoS）。
LOGIN_LOCK_SCOPE = config('LOGIN_LOCK_SCOPE', default='user_ip')

# ---------------------------------------------------------------------------
# 商談用アクセス（トークンURL + パスワード）
# ---------------------------------------------------------------------------
# 累計失敗が何回に達したらトークンを失効させるか
MEETING_REVOKE_THRESHOLD = config('MEETING_REVOKE_THRESHOLD', default=20, cast=int)
# 発行時の既定有効日数（絶対期限）
MEETING_EXPIRE_DAYS = config('MEETING_EXPIRE_DAYS', default=30, cast=int)
# 最終アクセスからこの日数が経過したら無効（無操作期限）。0 で無効化
MEETING_IDLE_DAYS = config('MEETING_IDLE_DAYS', default=7, cast=int)
# 発行するトークンの桁数（URLに載る値）。15桁で約77bit相当。
# 総当たりはロックと失効で抑えるため、URLの短さを優先している。
MEETING_TOKEN_LENGTH = config('MEETING_TOKEN_LENGTH', default=15, cast=int)
# 自動生成パスワードの桁数
MEETING_PASSWORD_LENGTH = config('MEETING_PASSWORD_LENGTH', default=16, cast=int)


# Email settings (development - console backend)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@dxits.com'


# Logging configuration（開発: コンソール出力）
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'app.rag_tr_tool': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
