# Generated by Django 5.1.11 on 2026-03-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField()),
                ('spec_snapshot', models.TextField()),
                ('mrr', models.FloatField()),
                ('recall_at_5', models.FloatField()),
            ],
        ),
    ]
