# Generated by Django 5.1.15 on 2026-07-03 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='EventDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('facility', '施設'), ('team', 'チーム')], max_length=10)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('recurrence_type', models.CharField(choices=[('weekly', '毎週'), ('monthly', '毎月')], max_length=10)),
                ('recurrence_days', models.JSONField(default=list)),
                ('effective_from', models.CharField(max_length=7)),
                ('effective_until', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event_definitions',
                'indexes': [models.Index(fields=['target_type', 'effective_from'], name='event_defin_target__f07618_idx')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='work_shift.team')),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_type', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='work_shift.staff')),
            ],
            options={
                'db_table': 'shifts',
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
