# Generated by Django 5.1.15 on 2026-07-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_shift', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventdefinition',
            new_name='wsft_event__target__ed875b_idx',
            old_name='event_defin_target__f07618_idx',
        ),
        migrations.AlterModelTable(
            name='eventdefinition',
            table='wsft_event_definitions',
        ),
        migrations.AlterModelTable(
            name='shift',
            table='wsft_shifts',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='wsft_staffs',
        ),
        migrations.AlterModelTable(
            name='team',
            table='wsft_teams',
        ),
    ]
