# Generated by Django 6.0.7 on 2026-07-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_shift', '0010_shift_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workshifttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
